# Generated by Django 6.1.1 on 2026-09-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='session',
            field=models.CharField(default='2025-2029', max_length=20),
        ),
    ]
